name: 'job-root-cache/restore'
author: 'Brian Espinosa'
description: 'Composite action that will restore a cache of the root directory to be used after clone and install.'

branding:
  icon: 'download-cloud'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    # Restore the cache of the root directory
    - uses: actions/cache/restore@v4
      with:
        path: ./
        key: job-setup-cache-${{ github.run_id }}-${{ runner.os }}

    # Set container to use the correct node version from cached .nvmrc
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
