# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Editing this file should manually trigger Dependabot to run again

version: 2
updates:
  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'brianespinosa'
    ignore:
      # Ignore updates to anything related to NX, as those updates should be run by hand.
      - dependency-name: '@nrwl*'
      - dependency-name: '@nx*'
      - dependency-name: 'nx'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps): update'
    groups:
      babel:
        patterns:
          - '@babel*'
          - 'babel*'
      eslint:
        patterns:
          - ^eslint-.*
          - ^@typescript-eslint/.*
          - ^eslint$
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      storybook:
        patterns:
          - ^@storybook/.*
          - ^storybook$
      stylelint:
        patterns:
          - ^stylelint-.*
          - ^stylelint$
      typescript:
        patterns:
          - ^@types/.*
          - ^typescript$
