# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'brianespinosa'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps): update'
    groups:
      storybook:
        patterns:
          - ^@storybook/.*
          - ^storybook$
      eslint:
        patterns:
          - ^eslint-.*
          - ^@typescript-eslint/.*
          - ^eslint$
      stylelint:
        patterns:
          - ^stylelint-.*
          - ^stylelint$
      typescript:
        patterns:
          - ^@types/.*
          - ^typescript$
