# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Editing this file should manually trigger Dependabot to run again

version: 2
updates:
  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      # Ignore updates to anything related to NX, as those updates should be run by hand.
      - dependency-name: '@nrwl*'
      - dependency-name: '@nx*'
      - dependency-name: 'nx'
      # Ignore updates to Cypress because Zscaler is trash and nobody knows how to allowlist it.
      - dependency-name: 'cypress'
      # Ignore typescript for now because it is most likely to generate a checksum that differs from CI environments, breaking immutable installs in Yarn.
      - dependency-name: 'typescript'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps): update'
    groups:
      # Due to how CI is currently set up using NX cloud, having many separate, or
      # even group PRs that come in at the same time can very quickly end up having
      # us hit our max number of concurrent connections (max 10) so setting everything
      # into one group should help us here, given we use 3 agents, plus one main agent.
      
      # UPDATE: No longer using NX Cloud. We might be okay with separate PRs now. but
      # we may need to update our CI to also do approvals and reviews in the same workflow.
      dependencies:
        # patterns:
        #   - '*'

      babel:
        patterns:
          - '@babel*'
          - 'babel*'
      eslint:
        patterns:
          - ^eslint-.*
          - ^@typescript-eslint/.*
          - ^eslint$
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      storybook:
        patterns:
          - ^@storybook/.*
          - ^storybook$
      stylelint:
        patterns:
          - ^stylelint-.*
          - ^stylelint$
      typescript:
        patterns:
          - ^@types/.*
          - ^typescript$
