# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Editing this file should manually trigger Dependabot to run again

version: 2
updates:
  - package-ecosystem: gitsubmodule
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'America/New_York'
    directory: /

  - package-ecosystem: npm
    rebase-strategy: 'auto'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      # Ignore updates to anything related to NX, as those updates should be run by hand.
      - dependency-name: '@nrwl*'
      - dependency-name: '@nx*'
      - dependency-name: 'nx'
      # Ignore any dependencies that are being managed with NX plugins:
      - dependency-name: 'cypress'
      - dependency-name: 'eslint'
      - dependency-name: 'jest'
      - dependency-name: 'next'
      - dependency-name: 'react-dom'
      - dependency-name: 'react'
      - dependency-name: 'typescript'
      - dependency-name: '*'
        versions: ['version-update:semver-major']
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): update'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel*'
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint-*'
          - 'eslint'
      react:
        patterns:
          - '@types/react-dom'
          - '@types/react'
          - 'react-dom'
          - 'react'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      stylelint:
        patterns:
          - 'stylelint-*'
          - 'stylelint'
      typescript:
        patterns:
          - '@types/*'
          - 'typescript'
