# https://github.com/arsenalamerica/.github
_extends: .github

repository:
  # The name of the repository. Changing this will rename the repository
  name: source

  # A short description of the repository that will show up on GitHub
  description: Arsenal America branch apps

  # A comma-separated list of topics to set on the repository
  topics: react, nextjs, typescript, multi-tenant, pwa

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Github UI Features
  has_issues: true
