defaultSemverRangePrefix: ''

logFilters:
  # This elevates missing peerDependency warnings to errors so we do not keep introducing them
  # https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
  - code: 'YN0002'
    level: 'error'

  # This elevates incompatible peerDependency warnings to errors so we do not keep introducing them.
  # These errors tell us we are using incompatible package versions together.
  # https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency
  - code: 'YN0060'
    level: 'error'

  # This is an old package that needs an update at some point
  - pattern: '*react-textfit*'
    level: 'discard'

nodeLinker: node-modules

packageExtensions:
  '@nrwl/cypress@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/devkit@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/eslint-plugin-nx@*':
    peerDependencies:
      '@typescript-eslint/parser': '*'
      eslint: '*'
      nx: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/jest@*':
    peerDependencies:
      nx: '*'
  '@nrwl/js@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/linter@*':
    peerDependencies:
      nx: '*'
  '@nrwl/next@*':
    peerDependencies:
      '@babel/core': '*'
      dotenv: '*'
      eslint: '*'
      express: '*'
      next: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
  '@nrwl/react@*':
    peerDependencies:
      '@types/node': '*'
      eslint: '*'
      nx: '*'
      webpack: '*'
  '@nrwl/web@*':
    peerDependencies:
      nx: '*'
  '@nx/cypress@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
  '@nx/eslint-plugin@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
  '@nx/jest@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/js@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
      '@types/node':
        optional: true
  '@nx/linter@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/next@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      dotenv: '*'
      eslint: '*'
      express: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true
  '@nx/react@*':
    peerDependencies:
      '@types/node': '*'
      eslint: '*'
      nx: '*'
      stylus: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      stylus:
        optional: true
      typescript:
        optional: true
  '@nx/web@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  react-textfit@*:
    peerDependencies:
      react: '^18.0.0'
      react-dom: '^18.0.0'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
