defaultSemverRangePrefix: ''

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0068
    level: error
  - level: discard
    pattern: '*react-textfit*'

nodeLinker: node-modules

packageExtensions:
  '@module-federation/enhanced@*':
    peerDependenciesMeta:
      '@rspack/core':
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
  '@module-federation/manifest@*':
    peerDependencies:
      typescript: '*'
  '@nx/cypress@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
      typescript: '*'
  '@nx/eslint-plugin@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
      typescript: '*'
  '@nx/eslint@*':
    peerDependencies:
      nx: '*'
  '@nx/jest@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/js@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@nx/module-federation@*':
    peerDependencies:
      nx: '*'
  '@nx/next@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      dotenv: '*'
      eslint: '*'
      express: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true
  '@nx/plugin@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      nx:
        optional: true
      typescript:
        optional: true
  '@nx/react@*':
    peerDependencies:
      '@types/node': '*'
      eslint: '*'
      nx: '*'
      stylus: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      stylus:
        optional: true
      typescript:
        optional: true
  '@nx/web@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@nx/webpack@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@swc-node/register@*':
    peerDependencies:
      '@swc/types': '*'
    peerDependenciesMeta:
      '@swc/types':
        optional: true
  react-textfit@*:
    peerDependencies:
      react: ^18.0.0
      react-dom: ^18.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'

yarnPath: .yarn/releases/yarn-3.8.3.cjs
