name: 'job-root-cache/cleanup'
author: 'Brian Espinosa'
description: 'Composite action that will remove/cleanup a cache of the root directory to be used after clone and install.'

branding:
  icon: 'download-cloud'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    # Remove the cache of the root directory
    - name: clear cache
      if: ${{ always() }}
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git init --bare
        gh extension install actions/gh-actions-cache
        gh actions-cache delete job-setup-cache-${{ github.run_id }}-${{ runner.os }} --confirm
