name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  main:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/nx-build.yml

  pr:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/nx-build.yml
    with:
      git-ref: ${{ github.event.pull_request.head.ref }}

  agents:
    uses: ./.github/workflows/nx-agents.yml
