name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - uses: actions/cache/save@v4
        with:
          path: ./
          key: job-setup-cache-${{ github.run_id }}-${{ runner.os }}

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: ./
          key: job-setup-cache-${{ github.run_id }}-${{ runner.os }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected --target=lint

  test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: ./
          key: job-setup-cache-${{ github.run_id }}-${{ runner.os }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected --target=test --ci
      # - name: Setup LCOV
      #   uses: hrishikesh-kadam/setup-lcov@v1
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v3
      #   with:
      #     coverage-files: coverage/**/lcov.info
      #     minimum-coverage: 90
      #     artifact-name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     working-directory: apps/my-first-app
      #     update-comment: true

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: ./
          key: job-setup-cache-${{ github.run_id }}-${{ runner.os }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx affected --target=build
      - name: clear cache
        if: ${{ success() }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete job-setup-cache-${{ github.run_id }}-${{ runner.os }} --confirm
