name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - uses: brianespinosa/job-root-cache/save@main

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=lint

  test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=test --ci
      # - name: Setup LCOV
      #   uses: hrishikesh-kadam/setup-lcov@v1
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v3
      #   with:
      #     coverage-files: coverage/**/lcov.info
      #     minimum-coverage: 90
      #     artifact-name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     working-directory: apps/my-first-app
      #     update-comment: true

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=build

  job-root-cache:
    needs:
      - lint
      - test
      - build
    uses: brianespinosa/job-root-cache/.github/workflows/cleanup.yml@main
