name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.15.0
    with:
      main-branch-name: main
      number-of-agents: 3
      install-commands: |
        yarn install --no-immutable
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="test" --agent-count=3
      # parallel-commands: |
      #   yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=3
        yarn nx affected --target=test --parallel=3 --ci --code-coverage

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.15.0
    with:
      number-of-agents: 3
