name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.set-shas.outputs.base }}
      head: ${{ steps.set-shas.outputs.head }}
      affectedApps: ${{ steps.affected.outputs.affectedApps }}
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - uses: nrwl/nx-set-shas@v4
        id: set-shas
      - name: Check for Affected Projects
        uses: 2coo/action-nx-affected@v1
        id: affected
        with:
          exclude: apps/branches-e2e,data
      - uses: brianespinosa/job-root-cache/save@main

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - env:
          AFFECTED: ${{ needs.setup.outputs.affectedApps }}
        run: echo "$AFFECTED"
      - run: yarn nx affected --target=lint --base=${{ needs.setup.outputs.base }} --head=${{ needs.setup.outputs.head }}

  test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=test --base=${{ needs.setup.outputs.base }} --head=${{ needs.setup.outputs.head }}
      # - name: Setup LCOV
      #   uses: hrishikesh-kadam/setup-lcov@v1
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v3
      #   with:
      #     coverage-files: coverage/**/lcov.info
      #     minimum-coverage: 90
      #     artifact-name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     working-directory: apps/my-first-app
      #     update-comment: true

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
      - lint
      - test
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=build --base=${{ needs.setup.outputs.base }} --head=${{ needs.setup.outputs.head }}

  job-root-cache:
    needs:
      - lint
      - test
      - build
    uses: brianespinosa/job-root-cache/.github/workflows/cleanup.yml@main
