name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    # if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target: 'minor'

  setup:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.set-shas.outputs.base }}
      head: ${{ steps.set-shas.outputs.head }}
      affectedApps: ${{ steps.affected.outputs.affectedApps }}
      hasAffectedApps: ${{ steps.affected.outputs.hasAffectedApps }}
    steps:
      - uses: brianespinosa/checkout-setup-node-install@main
      - uses: nrwl/nx-set-shas@v4
        id: set-shas
      - name: Check for Affected Projects
        uses: 2coo/action-nx-affected@v1
        id: affected
        with:
          exclude: apps/branches-e2e,data
      - uses: brianespinosa/job-root-cache/save@main

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=lint --base=${{ needs.setup.outputs.base }} --head=${{ needs.setup.outputs.head }}

  test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - run: yarn nx affected --target=test --base=${{ needs.setup.outputs.base }} --head=${{ needs.setup.outputs.head }}
      # - name: Setup LCOV
      #   uses: hrishikesh-kadam/setup-lcov@v1
      # - name: Report code coverage
      #   uses: zgosalvez/github-actions-report-lcov@v3
      #   with:
      #     coverage-files: coverage/**/lcov.info
      #     minimum-coverage: 90
      #     artifact-name: code-coverage-report
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     working-directory: apps/my-first-app
      #     update-comment: true

  build:
    if: ${{ needs.setup.outputs.hasAffectedApps == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    strategy:
      matrix:
        app: ${{ fromJson(needs.setup.outputs.affectedApps) }}
    environment:
      name: "${{ github.event_name != 'pull_request' && 'Production' || 'Preview' }} – ${{ matrix.app }}"
      url: ${{ steps.deploy-to-vercel.outputs.url }}
    needs:
      - setup
      - lint
      - test
    steps:
      - uses: brianespinosa/job-root-cache/restore@main
      - uses: brianespinosa/next-build-cache@main
      - name: Deploy to Vercel
        id: deploy-to-vercel
        run: |
          yarn nx deploy ${{ matrix.app }} --args="--token=${{ secrets.VERCEL_TOKEN }} ${{ github.event_name != 'pull_request' && '--prod' || '' }}"
          echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
      - name: Preview URL Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployment of ${{ matrix.app }} ready at: ${{ steps.deploy-to-vercel.outputs.url }}"
            })

  build-status:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Successful deployment(s)
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failed deployment(s)
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  job-root-cache:
    if: ${{ always() }}
    needs:
      - setup
      - lint
      - test
      - build
    uses: brianespinosa/job-root-cache/.github/workflows/cleanup.yml@main
