name: Reusable NX Agents Job

on:
  workflow_call:

jobs:
  nx-agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
