name: Reusable NX Build Job

on:
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string

jobs:
  nx-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=test --parallel --max-parallel=3
      - run: npx nx-cloud stop-all-agents

  nx-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=lint --parallel --max-parallel=3
      - run: npx nx-cloud stop-all-agents

  nx-build:
    runs-on: ubuntu-latest
    needs:
      - nx-lint
      - nx-test
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx nx-cloud stop-all-agents
